"""change outdoor time columns to string

Revision ID: 89d043d45015
Revises: c4682bc66f0e
Create Date: 2026-03-11 14:19:45.234595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89d043d45015'
down_revision: Union[str, Sequence[str], None] = 'c4682bc66f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outdoor_sessions', 'start_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('outdoor_sessions', 'end_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outdoor_sessions', 'end_time',
               existing_type=sa.String(length=5),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('outdoor_sessions', 'start_time',
               existing_type=sa.String(length=5),
               type_=postgresql.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
